"""Create checksum-based revision checkpoints when Git metadata is unavailable."""
from __future__ import annotations

import hashlib
import shutil
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FREEZE = ROOT / "revision_work/freeze"


def digest(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for b in iter(lambda: f.read(1024 * 1024), b""):
            h.update(b)
    return h.hexdigest()


def checkpoint(name: str, files: list[Path]) -> None:
    out = FREEZE / name
    out.mkdir(parents=True, exist_ok=True)
    rows = []
    for p in files:
        if not p.exists() or not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, target)
        rows.append({"path": str(rel), "bytes": p.stat().st_size, "sha256": digest(p)})
    pd.DataFrame(rows).to_csv(out / "SHA256SUMS.csv", index=False)
    (out / "README.md").write_text(
        f"# {name}\n\nImmutable-by-convention snapshot generated by "
        "`src/freeze_revision_checkpoints.py`; Git metadata was unavailable.\n",
        encoding="utf-8")


def main() -> None:
    checkpoint("figures-and-tables-freeze", [
        *sorted((ROOT / "paper/figures_revision").glob("*")),
        *sorted((ROOT / "paper/tables_revision").glob("*")),
        *sorted((ROOT / "revision_work/figure_source").glob("*")),
        ROOT / "results_manifest.csv",
    ])
    checkpoint("manuscript-rewrite", [
        ROOT / "paper/manuscript_revised_clean.md",
        ROOT / "paper/manuscript_revised_marked.md",
        ROOT / "paper/supplement_revised.md",
        ROOT / "paper/cover_letter_revised.md",
        ROOT / "paper/title_page_revised.md",
    ])
    checkpoint("response-letter", [ROOT / "paper/response_to_reviewers.md"])
    checkpoint("submission-QA", [
        *sorted((ROOT / "paper/docx_revision").glob("*.docx")),
        ROOT / "analysis_environment.yml", ROOT / "requirements.txt",
        ROOT / "REVISION_CHANGELOG.md", ROOT / "results_manifest.csv",
    ])
    print("created figures-and-tables, manuscript, response, and submission-QA checkpoints")


if __name__ == "__main__":
    main()
